#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend michaelglory.tech
    timeout client  30000
    bind 0:80
    default_backend michaelglory.tech_backend

backend michaelglory.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 228560-web-01 54.160.97.141:80 check
    server 228560-web-02 18.233.64.80:80 check
EOT

sudo service haproxy restart
