#!/usr/bin/env bash
# Use sed to replace occurrences of '8080' with '80' in the Nginx default
# site configuration
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the updated configuration
service nginx restart

# Terminate the oldest (least recently started) Nginx process to ensure
# the changes take effect
pkill -o nginx
