#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely
# Add a sleep 2 inbetween each iteration

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done